### ISSUE TITLE
Tray icon stalls (sometimes)

### ISSUE THREAD

**Issue by kindkaktus** [klemensschindler/tomatron#11] opened 2015-09-11 11:21 UTC
I noticed that after the app's tray icon sometimes stops reacting on mouse clicks. This happened twice within 5 days. Sadly it can't be easily reproduced. Restarting the app works around the problem.

Windows 7 Pro 64-bit
Tomatron version: 1.1

**Comment by klemensschindler** [comment] 2016-08-30 20:24
I also observed the problem a few times. I could not get to the bottom of the issue, but Tomatron 1.2 revises the way the tray icon entries are updated. Could you try if the issue still exists in 1.2?

**Comment by kindkaktus** [comment] 2016-09-01 06:46
Thank you for the update. Just installed 1.2. I will let you know if I come across the tray issue again. Environment: Windows 10 Home, Oracle Java 8 update 110

**Comment by klemensschindler** [comment] 2016-09-08 16:34
It seems that the issue was not seen anymore. I'm closing the issue. If the problem is not solved, feel free to re-open the issue.

**Closed as completed by klemensschindler** 2016-09-08 16:34 UTC

**Comment by kindkaktus** [comment] 2016-11-29 07:43
Unfortunately the issue still persists. After my PC came out from stand bytomatron tray icon is still visible, hover tooltip is shown but the icon does not react on mouse clicks.
Tomatron 1.2, Windows 7 x64
